name: '[Test] Test siibra-tutorials'

on:
  push:
    branches: ["**"]
  workflow_dispatch:
    inputs:
      siibra_python_branch:
        description: 'siibra-python branch to use'
        required: false
        default: 'main'
        type: string


jobs:
  test_tutorials:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/FZJ-INM1-BDA/siibra-python.git@${{ inputs.siibra_python_branch }}
          pip install siibra_jugex
          pip install matplotlib
          pip install pytest nbmake

      - name: Test tutorial notebooks with nbmake
        run: pytest --nbmake --nbmake-timeout=1200 ./
